#!/bin/bash

echo "═══════════════════════════════════════════════════════════"
echo "  🚀 Android Bank Payment Integration - Quick Setup"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Check if Node.js is running
echo "🔍 Checking if API server is running..."
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null ; then
    echo "✅ API Server is running on port 3000"
else
    echo "❌ API Server NOT running!"
    echo ""
    echo "📝 To start the API server:"
    echo "   npm start"
    echo "   or"
    echo "   node src/server.js"
    echo ""
    exit 1
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  📋 Next Steps:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  IMPORT POSTMAN COLLECTION"
echo "   └─ File: Bank_Payment_Android_Integration.postman_collection.json"
echo "   └─ Steps:"
echo "       • Open Postman"
echo "       • Click Import (top left)"
echo "       • Select the JSON file"
echo "       • Click Import"
echo ""

echo "2️⃣  TEST IN POSTMAN"
echo "   └─ Follow: POSTMAN_TESTING_GUIDE.md"
echo "   └─ Run these requests in order:"
echo "       1. Login User"
echo "       2. Create Order - ₹500"
echo "       3. Complete payment on Razorpay"
echo "       4. Verify Payment"
echo "   └─ Test card: 4111111111111111"
echo ""

echo "3️⃣  INTEGRATE INTO ANDROID"
echo "   └─ Follow: ANDROID_INTEGRATION_CHECKLIST.md"
echo "   └─ Steps:"
echo "       1. Add Razorpay dependency"
echo "       2. Create model classes"
echo "       3. Create API service"
echo "       4. Create Payment Activity"
echo "       5. Test on emulator/device"
echo ""

echo "4️⃣  DOCUMENTATION"
echo "   └─ ANDROID_QUICK_REFERENCE.md - For quick lookup"
echo "   └─ ANDROID_INTEGRATION_README.md - Overview"
echo "   └─ POSTMAN_TESTING_GUIDE.md - API testing guide"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  🔗 API Endpoints"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Base URL: http://localhost:3000/api"
echo ""
echo "POST   /auth/login"
echo "POST   /payments/create-order"
echo "POST   /payments/verify"
echo "GET    /payments"
echo "GET    /payments/:paymentId"
echo "GET    /payments/order/:orderId"
echo "POST   /payments/:paymentId/refund"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  💳 Test Card Details"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Card Number: 4111111111111111"
echo "Expiry: 12/25 (any future date)"
echo "CVV: 123"
echo ""
echo "UPI: success@razorpay"
echo "Net Banking: Select any bank"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  ✅ Everything is ready!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Start testing in Postman: 👉 Bank_Payment_Android_Integration.postman_collection.json"
echo ""
