module.exports.NOTIFICATION_TYPES = {
  // Ticket Related
  TICKET_CONFIRMED: "TICKET_CONFIRMED",
  TICKET_ISSUED: "TICKET_ISSUED",
  TICKET_CANCELLED: "TICKET_CANCELLED",

  // Face Verification
  FACE_VERIFICATION_REJECTED: "FACE_VERIFICATION_REJECTED",
  FACE_VERIFICATION_APPROVED: "FACE_VERIFICATION_APPROVED",
  FACE_VERIFICATION_SUBMITTED: "FACE_VERIFICATION_SUBMITTED",

  // Registration Related
  REGISTRATION_CONFIRMED: "REGISTRATION_CONFIRMED",
  REGISTRATION_REJECTED: "REGISTRATION_REJECTED",
  REGISTRATION_AWAITING_PAYMENT: "REGISTRATION_AWAITING_PAYMENT",

  // Event Related
  SHOW_FULL: "SHOW_FULL",
  EVENT_UPDATED: "EVENT_UPDATED",
  EVENT_CANCELLED: "EVENT_CANCELLED",

  // Refund Related
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_COMPLETED: "REFUND_COMPLETED",

  // Waitlist Related
  WAITLIST_OFFER: "WAITLIST_OFFER",
  WAITLIST_POSITION_UPDATED: "WAITLIST_POSITION_UPDATED",

  // Admin Actions
  USER_ACCOUNT_CREATED: "USER_ACCOUNT_CREATED",
  USER_ACCOUNT_UPDATED: "USER_ACCOUNT_UPDATED",
  USER_ACCOUNT_SUSPENDED: "USER_ACCOUNT_SUSPENDED",

  // Generic categories used by the public API (not templates)
  UTILITY: "UTILITY",
  BATCH: "BATCH" // marketing/broadcast no storage
};
